#pragma once

enum Batsman_Sort_Choice
{
    BATTING_AVERAGE = 0,
    STRIKING_RATES,
    MAX_6S_AND_4S,
    STRIKE_RATES_WITH_6S_AND_4S,
    AVERAGES_WITH_STRIKE_RATES,
    MAX_RUNS_AND_AVERAGE
};

enum Bowler_Sort_Choice
{
    AVERAGE = 0,
    BOWLING_STRIKE_RATE,
    ECONOMY_RATE,
    SR_WITH_5W_AND_4W
};