#pragma once

enum Batsman_Sort_Choice
{
    BATTING_AVERAGE = 0,
    STRIKING_RATES,
    MAX_6S_AND_4S,
    STRIKE_RATES_WITH_6S_AND_4S,
    AVERAGES_WITH_STRIKE_RATES,
    MAX_RUNS_AND_AVERAGE,
    MAX_100S_AND_BAT_AVERAGES
};

enum Bowler_Sort_Choice
{
    AVERAGE = 0,
    BOWLING_STRIKE_RATE,
    ECONOMY_RATE,
    SR_WITH_5W_AND_4W,
    AVERAGE_WITH_STRIKE_RATE,
    MAX_WKTS_WITH_AVG
};

enum Allrounder_Sort_Choice
{
    BATTING_AND_BOWLING_AVG = 0,
    MOST_RUNS_AND_WICKETS
};